### ISSUE TITLE
error caught with rnafeatures.py 

### ISSUE THREAD

**Issue by xflicsu** [gianlucacorrado/RNAcommender#2]
When I run the fellow command, I caught errors.

$python rnacommender/rnafeatures.py examples/utrs.fa examples/utrs.h5

###################################################
/panfs/home/sun/wujinyu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/panfs/home/sun/wujinyu/anaconda2/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
Folding sequences using RNAplfold -W 100 -L 40 -c 0.400000                 --noLP... Done.

Vectorizing (complexity: 2, hashing: 10 bits)... 
#--------------------------------------------------------------------------------
object of type 'generator' has no len()
Error in: uc001abw.1_3UTR GGUUGCCGGGGGUAGGGGUGGGGCCACACAAAUCUCCAGGAGCCACCACUCAACACAAUGGCCCUGCCUCCCACCGCUUUAUUUCUUUCGGUUUCGGAUGCAAAACAAAAAAUUUUAAAAGAAAAUGUGACUUCAAAGGAAAGGAACAAAUUUUCAAAGACUUGGGGGAGUGAAGGCAGAGCCUGGUGCAGAUGGACGAGGUCUGCAGACGGAGGGCAGAGGUGGUGGAAGGGGCCAGGGGCCUGCAGGCCUCCCCCUGGAACUGGGACUGGUCUCGGUCUGCUGACGUCAGGGUCAGCUCCCCCGCGGAGCUGACUUCAGCAGCCCACAGCUGUGGGGCUUCAGCAGCCACACCAGCCCAGCCCAGCCCAGCUCUCGAUACGUUUGGUCUUUCAUGCUGAAAAAUAAAUAAUAAAGCCUGUCCCGUG
Reverting to path graph from sequence
WARNING: window size 100 larger than sequence length 80

#--------------------------------------------------------------------------------
object of type 'generator' has no len()
Error in: uc001abw.1_5UTR GCAGAUCCCUGCGGCGUUCGCGAGGGUGGGACGGGAAGCGGGCUGGGAAGUCGGGCCGAGGGAAAAGUCUGAAGACGCUU
Reverting to path graph from sequence
##########################################################

So, how to fix this bug?
Thanks!

**Comment by gianlucacorrado** [comment]
These are errors are generated because of RNAplfold. The messages you are seeing are the error handling implemented in the [rnaplfold converter of EDeN](https://github.com/fabriziocosta/EDeN/blob/master/eden/converter/rna/rnaplfold.py). 

When, for some reason, it was not possible to generate the graph encoding of the predicted folded structure of the RNA, EDeN generates a path graph from the RNA sequence. A path graph is just the graph representation of a sequence and it can be used with the graph vectorizer (as the other correctly generated graphs).

Anyway, these errors are not supposed to halt the computation of the RNA features, and, at the end, you will have a feature vector for each RNA sequence in the input fasta file. For sequences that raised RNAplfold errors, those features are computed from the sequence information only.

Cheers
