### ISSUE TITLE
cutoff of recommendations result?

### ISSUE THREAD

**Issue by xflicsu** [gianlucacorrado/RNAcommender#3]
I use the fellow command to output the predicted result.
###
python recommend.py ../examples/rbps_new.h5  ../examples/utrs.h5 ../examples/trained_from_AURA_HT.pkl --output ../examples/recommendations.txt --standardize-Fr
###
#####
RBP     target  y_hat   serendipity
Pcbp2      uc008jda.1_3UTR_Tor1b   0.992   1.00
Fus           uc011wjf.1_3UTR_Fam168b 0.979   1.00
Fus           uc007apj.2_3UTR_Fam168b 0.979   1.00
Fus           uc011wje.1_3UTR_Fam168b 0.979   1.00
.....
Fus           uc009ouj.1_5UTR_Tmem218 0.000   1.00
Fus           uc007yxk.2_5UTR_Bdh1    0.000   1.00
Fus           uc008qoy.2_5UTR_Fmo5    0.000   1.00
Pcbp2      uc009fqd.1_5UTR_Phldb3  0.000   1.00
Rbm3       uc009qqk.3_3UTR_Ccpg1os 0.000   1.00
#####
So, how to set the cutoff to select the high-credible interactions of RBPs and  RNA?

**Comment by gianlucacorrado** [comment]
RNAcommender outputs a ranking. The higher the prediction score, the more accurate the prediction should be. Anyway the prediction score is in the range [0,1] (obtained with a sigmoid).
![main-qimg-05edc1873d0103e36064862a45566dba](https://cloud.githubusercontent.com/assets/17332283/21764918/f43281ba-d665-11e6-877a-e8118b34b0bd.gif)

The threshold value may vary depending on the considered dataset. In the paper we did not analyse the relationship between a selected threshold and the corresponding accuracy of the method, especially because it is not straightforward to set a threshold. If you need cast the ranking problem analysed in RNAcommender into a strict classification task where you identify positives and negatives you may try two options:

1.  Select a fixed threshold (e.g. 0.5), or a different value depending on your needs regarding the precision/recall tradeoff.
2. Find the threshold that gives an acceptable accuracy on a validation set extracted from the dataset

Cheers.
