### ISSUE TITLE
Building model with AURA data sets consume lots of times

### ISSUE THREAD

**Issue by xflicsu** [gianlucacorrado/RNAcommender#4]
Hello,
     I use RNAcommender to predict RBP-RNA interaction.
     To take advantage of known interactions from AURA database, I building the model with 167  RBPs (human + mouse) and their 67111 targeting UTRs.
     And the RNA features step consume lots of time (30 hours), and it is still running.
#####
python rnacommender/rnafeatures.py --njobs 20 $AURA/UTR.target.fa $AURA/UTR.target.h5
#####
     I wonder whether there is other ways to accelerate this process?

**Comment by gianlucacorrado** [comment]
Hello again,
vectorizing 67k sequences requires time (possibly days), especially because the wrapper around RNAplfold is not running in multi-thread. This is due to RNAplfold behaviour of writing to disk, so multi-threading will try to access the same file for multiple sequences. One walkaround I used during generation of the features for the 72k UTRs was to split the fasta file into 10 parts and put them in separate directories, and then call rnafeatures.py --njobs 1 from inside the directories. In this case the wrapper of RNAplfold will create 10 copies of the RNAplfold output file that are spread over the 10 directories. In the end you will get 10 different h5 files containing the features. Each h5 file will contain a pandas DataFrame with the features of some of the UTRs. Then you can manually aggregate them into a single pandas DataFrame and save it in a new h5 file that can be used with RNAcommender.

I hope this is clear enough
Cheers

**Comment by xflicsu** [comment]
I have got 14 h5 files by following your suggestion.
I am not familiar with python.
So, could you paste a python script to merge those h5 files?
Thanks again!

**Comment by gianlucacorrado** [comment]
This is the python code (python 2.7) that merges the h5 files. You just have to change the names of the input and output h5 files.
```
import pandas as pd
# list of file names of the h5 stores to aggregate
parts = ["part01.h5", "part02.h5", ... ,"part14.h5"] # change file names here

# read all the parts and load the DataFrames into a list
dataframes = list()
for p in parts:
    store = pd.io.pytables.HDFStore(p)
    dataframes.append(store.features)
    store.close()

# concatenate the DataFrames by column
aggregated = pd.concat(dataframes, axis=1)

# save a new h5 store containing the aggregated DataFrame
newstore = pd.io.pytables.HDFStore("aggregated.h5") # change file name here
newstore["features"] = aggregated
newstore.close()
```
